In [1]:
import pandas as pd

In [2]:
df_main = pd.read_csv("C:\\Users\\Lenovo\\Desktop\\Reputation System\\final\\filecoin_messages_cleaned_jan22jan24_compiled1.csv")
attribute_df = df_main.loc[:, ['date', 'sender_account', 'sender_address', 'sender_type', 'receiver_account', 'receiver_address', 'receiver_type', 'method_name']]

In [3]:
df=pd.read_csv("C:\\Users\\Lenovo\\Desktop\\Reputation System\\final\\full_kproto_clusters.csv")

In [4]:
value_counts = df['K Prototypes'].value_counts()

print(value_counts)

K Prototypes
0    1377113
1     677496
3     320324
2     197864
4      83203
Name: count, dtype: int64

In [5]:
nan_count = df['K Prototypes'].isna().sum()

print("Number of NaN values in 'K Prototypes' column:", nan_count)

Number of NaN values in 'K Prototypes' column: 0

In [6]:
df['success'] = df['success'].astype(int)

In [7]:
columns_to_encode = ['method_id', 'success', 'exitCode']

# Perform one-hot encoding
one_hot_encoded_df = pd.get_dummies(df, columns=columns_to_encode)*1

In [8]:
one_hot_encoded_df.columns

Index(['Unnamed: 0', 'refundDecimal', 'refund', 'amountDecimal',
       'burnedDecimal', 'overEstimationBurn', 'baseFeeBurn', 'minerPenalty',
       'minerTip', 'K Prototypes', 'method_id_0', 'method_id_1', 'method_id_2',
       'method_id_3', 'method_id_4', 'method_id_5', 'method_id_6',
       'method_id_7', 'method_id_8', 'method_id_9', 'method_id_11',
       'method_id_15', 'method_id_16', 'method_id_18', 'method_id_19',
       'method_id_20', 'method_id_21', 'method_id_22', 'method_id_23',
       'method_id_24', 'method_id_25', 'method_id_26', 'method_id_27',
       'method_id_28', 'method_id_30', 'method_id_32', 'method_id_872461',
       'method_id_3844450837', 'success_0', 'success_1', 'exitCode_0',
       'exitCode_5', 'exitCode_6', 'exitCode_7', 'exitCode_8', 'exitCode_16',
       'exitCode_17', 'exitCode_18', 'exitCode_19', 'exitCode_20',
       'exitCode_21', 'exitCode_22', 'exitCode_32', 'exitCode_33',
       'exitCode_34', 'exitCode_36'],
      dtype='object')

In [9]:
import pandas as pd

# Group by 'sender_account' and calculate count and mean for each group
grouped_df_comb = one_hot_encoded_df.groupby('K Prototypes').agg({
    'refundDecimal': 'mean',
    'refund': 'mean',
    'amountDecimal': 'mean',
    'burnedDecimal': 'mean',
    'overEstimationBurn': 'mean',
    'baseFeeBurn': 'mean',
    'success_0': 'mean',
    'success_1': 'mean',
    'minerPenalty': 'mean',
    'minerTip': 'mean',
    'method_id_0': 'mean',
    'method_id_1': 'mean',
    'method_id_2': 'mean',
    'method_id_3': 'mean', 
    'method_id_4': 'mean', 
    'method_id_5': 'mean', 
    'method_id_6': 'mean',
    'method_id_7': 'mean', 
    'method_id_8': 'mean', 
    'method_id_9': 'mean', 
    'method_id_11': 'mean',
    'method_id_15': 'mean', 
    'method_id_16': 'mean', 
    'method_id_18': 'mean', 
    'method_id_19': 'mean',
    'method_id_20': 'mean', 
    'method_id_21': 'mean',
    'method_id_22': 'mean', 
    'method_id_23': 'mean',
    'method_id_24': 'mean', 
    'method_id_25': 'mean', 
    'method_id_26': 'mean', 
    'method_id_27': 'mean',
    'method_id_28': 'mean', 
    'method_id_30': 'mean', 
    'method_id_32': 'mean', 
    'method_id_872461': 'mean',
    'method_id_3844450837': 'mean',
    'exitCode_0': 'mean',
    'exitCode_5': 'mean',
    'exitCode_6': 'mean',
    'exitCode_7': 'mean', 
    'exitCode_8': 'mean', 
    'exitCode_16': 'mean', 
    'exitCode_17': 'mean', 
    'exitCode_18': 'mean',
    'exitCode_19': 'mean', 
    'exitCode_20': 'mean', 
    'exitCode_21': 'mean', 
    'exitCode_22': 'mean',
    'exitCode_32': 'mean', 
    'exitCode_33': 'mean', 
    'exitCode_34': 'mean', 
    'exitCode_36': 'mean'})



# Reset index to make 'sender_account' a regular column
grouped_df_comb.reset_index(inplace=True)



# Display the result
grouped_df_comb.head()

,K Prototypes,refundDecimal,refund,amountDecimal,burnedDecimal,overEstimationBurn,baseFeeBurn,success_0,success_1,minerPenalty,...,exitCode_17,exitCode_18,exitCode_19,exitCode_20,exitCode_21,exitCode_22,exitCode_32,exitCode_33,exitCode_34,exitCode_36
0,0,4.514631e-07,4.514631e-07,2.354693e-05,2.471438e-07,7.987966e-07,8.620346e-08,0.007123,0.992877,1.619307e-09,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,1,2.284361e-04,2.284361e-04,4.439818e-08,1.414998e-04,3.052677e-05,1.403997e-04,0.019574,0.980426,3.908790e-06,...,0.000015,0.000055,0.000019,0.000038,0.000000,0.000000,0.000001,0.000000,0.000000,0.000001
2,2,2.458487e-06,2.458487e-06,3.190281e-06,9.359719e-06,5.731869e-06,8.495005e-06,0.033897,0.966103,1.212981e-06,...,0.000313,0.000152,0.000035,0.000061,0.000000,0.000000,0.000005,0.011735,0.000005,0.000000
3,3,7.131514e-06,7.131514e-06,4.027867e-08,6.597868e-06,1.540255e-06,6.521647e-06,0.010283,0.989717,1.224122e-08,...,0.001561,0.001052,0.000983,0.000178,0.000003,0.000022,0.000006,0.000000,0.000000,0.000000
4,4,4.400176e-03,4.400176e-03,9.194905e-06,4.918178e-03,1.635594e-03,4.757381e-03,0.108133,0.891867,3.252139e-04,...,0.002308,0.000132,0.000024,0.000048,0.000000,0.000012,0.000000,0.000000,0.000000,0.000000

In [10]:

# Assuming you already have 'grouped_df_comb' DataFrame
# Initialize an empty DataFrame to store the rankings
mega_df = pd.DataFrame()

rank_columns=['refundDecimal', 'amountDecimal',
       'burnedDecimal', 'overEstimationBurn', 'baseFeeBurn', 'success_0',
       'success_1', 'minerPenalty', 'minerTip', 'method_id_0',
       'method_id_2', 'method_id_4', 'method_id_5',
       'method_id_6', 
       'method_id_11', 'method_id_15',
       'method_id_19',  'method_id_21', 'method_id_22',
        'exitCode_0', 'exitCode_5',
       'exitCode_6', 'exitCode_7', 'exitCode_8', 'exitCode_16', 'exitCode_17',
       'exitCode_18', 'exitCode_19', 'exitCode_20', 'exitCode_21',
       'exitCode_22', 'exitCode_32', 'exitCode_33', 'exitCode_34',
       'exitCode_36']

one_hot_encoded_kproto = grouped_df_comb[rank_columns].copy()

for i in rank_columns:
    # Group by 'K Means Class' and rank each column
    ranked_df = grouped_df_comb[i].rank(method='max', ascending=False)
    # Append the ranked column to mega_df
    mega_df[i] = ranked_df

# Now mega_df contains the rankings for each column in columns_to_rank for each cluster
print(mega_df)

   refundDecimal  amountDecimal  burnedDecimal  overEstimationBurn  \
0            5.0            1.0            5.0                 5.0
1            2.0            4.0            2.0                 2.0
2            4.0            3.0            3.0                 3.0
3            3.0            5.0            4.0                 4.0
4            1.0            2.0            1.0                 1.0

   baseFeeBurn  success_0  success_1  minerPenalty  minerTip  method_id_0  \
0          5.0        5.0        1.0           5.0       5.0          1.0
1          2.0        3.0        3.0           2.0       2.0          5.0
2          3.0        2.0        4.0           3.0       3.0          5.0
3          4.0        4.0        2.0           4.0       4.0          5.0
4          1.0        1.0        5.0           1.0       1.0          2.0

   ...  exitCode_17  exitCode_18  exitCode_19  exitCode_20  exitCode_21  \
0  ...          5.0          5.0          5.0          5.0          5.0
1  ...          4.0          4.0          4.0          4.0          5.0
2  ...          3.0          2.0          2.0          2.0          5.0
3  ...          2.0          1.0          1.0          1.0          1.0
4  ...          1.0          3.0          3.0          3.0          5.0

   exitCode_22  exitCode_32  exitCode_33  exitCode_34  exitCode_36
0          5.0          5.0          5.0          5.0          5.0
1          5.0          3.0          5.0          5.0          1.0
2          5.0          2.0          1.0          1.0          5.0
3          1.0          1.0          5.0          5.0          5.0
4          2.0          5.0          5.0          5.0          5.0

[5 rows x 35 columns]

In [11]:
positive_weight_columns = ['amountDecimal', 'success_1', 'minerTip', 'method_id_0', 'method_id_2', 'method_id_4',
                           'method_id_5', 'method_id_6', 'method_id_19', 'method_id_21', 'exitCode_0']

negative_weight_columns = ['refundDecimal', 'overEstimationBurn', 'success_0', 'minerPenalty', 'method_id_11',
                           'method_id_15', 'method_id_22', 'exitCode_5', 'exitCode_6', 'exitCode_7', 'exitCode_8',
                           'exitCode_16', 'exitCode_17', 'exitCode_18', 'exitCode_19', 'exitCode_20', 'exitCode_21',
                           'exitCode_22', 'exitCode_32', 'exitCode_33', 'exitCode_34', 'exitCode_36']

In [12]:
for col in negative_weight_columns:
    mega_df[col] *= -1  # Multiply the column by -1

# Now mega_df contains the rankings for each column
print(mega_df)

   refundDecimal  amountDecimal  burnedDecimal  overEstimationBurn  \
0           -5.0            1.0            5.0                -5.0
1           -2.0            4.0            2.0                -2.0
2           -4.0            3.0            3.0                -3.0
3           -3.0            5.0            4.0                -4.0
4           -1.0            2.0            1.0                -1.0

   baseFeeBurn  success_0  success_1  minerPenalty  minerTip  method_id_0  \
0          5.0       -5.0        1.0          -5.0       5.0          1.0
1          2.0       -3.0        3.0          -2.0       2.0          5.0
2          3.0       -2.0        4.0          -3.0       3.0          5.0
3          4.0       -4.0        2.0          -4.0       4.0          5.0
4          1.0       -1.0        5.0          -1.0       1.0          2.0

   ...  exitCode_17  exitCode_18  exitCode_19  exitCode_20  exitCode_21  \
0  ...         -5.0         -5.0         -5.0         -5.0         -5.0
1  ...         -4.0         -4.0         -4.0         -4.0         -5.0
2  ...         -3.0         -2.0         -2.0         -2.0         -5.0
3  ...         -2.0         -1.0         -1.0         -1.0         -1.0
4  ...         -1.0         -3.0         -3.0         -3.0         -5.0

   exitCode_22  exitCode_32  exitCode_33  exitCode_34  exitCode_36
0         -5.0         -5.0         -5.0         -5.0         -5.0
1         -5.0         -3.0         -5.0         -5.0         -1.0
2         -5.0         -2.0         -1.0         -1.0         -5.0
3         -1.0         -1.0         -5.0         -5.0         -5.0
4         -2.0         -5.0         -5.0         -5.0         -5.0

[5 rows x 35 columns]

In [13]:
# Define the mapping dictionary
value_mapping = {1: 4, 2: 3, 3: 2, 4: 1, 5: 0, -1:-4, -2:-3, -3:-2, -4:-1, -5:0}

# Apply the mapping to the DataFrame
mapped_df = mega_df.replace(value_mapping)


print(mapped_df)

   refundDecimal  amountDecimal  burnedDecimal  overEstimationBurn  \
0            0.0            4.0            0.0                 0.0
1           -3.0            1.0            3.0                -3.0
2           -1.0            2.0            2.0                -2.0
3           -2.0            0.0            1.0                -1.0
4           -4.0            3.0            4.0                -4.0

   baseFeeBurn  success_0  success_1  minerPenalty  minerTip  method_id_0  \
0          0.0        0.0        4.0           0.0       0.0          4.0
1          3.0       -2.0        2.0          -3.0       3.0          0.0
2          2.0       -3.0        1.0          -2.0       2.0          0.0
3          1.0       -1.0        3.0          -1.0       1.0          0.0
4          4.0       -4.0        0.0          -4.0       4.0          3.0

   ...  exitCode_17  exitCode_18  exitCode_19  exitCode_20  exitCode_21  \
0  ...          0.0          0.0          0.0          0.0          0.0
1  ...         -1.0         -1.0         -1.0         -1.0          0.0
2  ...         -2.0         -3.0         -3.0         -3.0          0.0
3  ...         -3.0         -4.0         -4.0         -4.0         -4.0
4  ...         -4.0         -2.0         -2.0         -2.0          0.0

   exitCode_22  exitCode_32  exitCode_33  exitCode_34  exitCode_36
0          0.0          0.0          0.0          0.0          0.0
1          0.0         -2.0          0.0          0.0         -4.0
2          0.0         -3.0         -4.0         -4.0          0.0
3         -4.0         -4.0          0.0          0.0          0.0
4         -3.0          0.0          0.0          0.0          0.0

[5 rows x 35 columns]

In [14]:
mapped_df['sum'] = mapped_df.sum(axis=1)

# Print the DataFrame with the new 'sum' column
print(mapped_df)

   refundDecimal  amountDecimal  burnedDecimal  overEstimationBurn  \
0            0.0            4.0            0.0                 0.0
1           -3.0            1.0            3.0                -3.0
2           -1.0            2.0            2.0                -2.0
3           -2.0            0.0            1.0                -1.0
4           -4.0            3.0            4.0                -4.0

   baseFeeBurn  success_0  success_1  minerPenalty  minerTip  method_id_0  \
0          0.0        0.0        4.0           0.0       0.0          4.0
1          3.0       -2.0        2.0          -3.0       3.0          0.0
2          2.0       -3.0        1.0          -2.0       2.0          0.0
3          1.0       -1.0        3.0          -1.0       1.0          0.0
4          4.0       -4.0        0.0          -4.0       4.0          3.0

   ...  exitCode_18  exitCode_19  exitCode_20  exitCode_21  exitCode_22  \
0  ...          0.0          0.0          0.0          0.0          0.0
1  ...         -1.0         -1.0         -1.0          0.0          0.0
2  ...         -3.0         -3.0         -3.0          0.0          0.0
3  ...         -4.0         -4.0         -4.0         -4.0         -4.0
4  ...         -2.0         -2.0         -2.0          0.0         -3.0

   exitCode_32  exitCode_33  exitCode_34  exitCode_36   sum
0          0.0          0.0          0.0          0.0   7.0
1         -2.0          0.0          0.0         -4.0 -11.0
2         -3.0         -4.0         -4.0          0.0 -29.0
3         -4.0          0.0          0.0          0.0 -30.0
4          0.0          0.0          0.0          0.0 -10.0

[5 rows x 36 columns]

Without Exit Codes

In [15]:
#what if i remove the exit codes
without_exit=mapped_df.drop(columns=['exitCode_5', 'exitCode_6', 'exitCode_7', 'exitCode_8',
                           'exitCode_16', 'exitCode_17', 'exitCode_18', 'exitCode_19', 'exitCode_20', 'exitCode_21',
                           'exitCode_22', 'exitCode_32', 'exitCode_33', 'exitCode_34', 'exitCode_36'])
without_exit['sum'] = without_exit.sum(axis=1)

# Print the DataFrame with the new 'sum' column
print(without_exit)

   refundDecimal  amountDecimal  burnedDecimal  overEstimationBurn  \
0            0.0            4.0            0.0                 0.0
1           -3.0            1.0            3.0                -3.0
2           -1.0            2.0            2.0                -2.0
3           -2.0            0.0            1.0                -1.0
4           -4.0            3.0            4.0                -4.0

   baseFeeBurn  success_0  success_1  minerPenalty  minerTip  method_id_0  \
0          0.0        0.0        4.0           0.0       0.0          4.0
1          3.0       -2.0        2.0          -3.0       3.0          0.0
2          2.0       -3.0        1.0          -2.0       2.0          0.0
3          1.0       -1.0        3.0          -1.0       1.0          0.0
4          4.0       -4.0        0.0          -4.0       4.0          3.0

   ...  method_id_4  method_id_5  method_id_6  method_id_11  method_id_15  \
0  ...          0.0          0.0          0.0           0.0           0.0
1  ...          1.0          4.0          2.0          -2.0          -2.0
2  ...          2.0          0.0          1.0          -3.0          -3.0
3  ...          3.0          0.0          3.0          -4.0          -4.0
4  ...          4.0          3.0          4.0          -1.0           0.0

   method_id_19  method_id_21  method_id_22  exitCode_0   sum
0           0.0           0.0          -3.0         4.0  20.0
1           1.0           0.0           0.0         2.0  -4.0
2           3.0           0.0           0.0         1.0 -27.0
3           4.0           4.0          -4.0         3.0 -20.0
4           2.0           0.0           0.0         0.0   4.0

[5 rows x 21 columns]

In [16]:
mapping = {
    0: 1,
    1: 0.5,
    2: 0,
    3: 0.25,
    4: 0.75
}

# Map 'K Means Class' column
df['K Prototypes'] = df['K Prototypes'].map(mapping)

In [17]:
df.head()

,Unnamed: 0,method_id,refundDecimal,refund,amountDecimal,burnedDecimal,overEstimationBurn,baseFeeBurn,success,minerPenalty,minerTip,exitCode,K Prototypes
0,0,0,5.153828e-15,5.153831e-15,8.707997e-07,1.909200e-14,1.822014e-15,1.943351e-14,1,0.0,1.526450e-10,0,1.0
1,1,0,1.651061e-13,1.651061e-13,7.272510e-06,1.127853e-13,1.984154e-14,1.128663e-13,1,0.0,1.001534e-09,0,1.0
2,2,0,2.229661e-14,2.229661e-14,5.608440e-10,1.985343e-14,3.492619e-15,1.986773e-14,1,0.0,1.401671e-10,0,1.0
3,3,0,4.518457e-14,4.518457e-14,5.803177e-07,4.086698e-14,7.189436e-15,4.089633e-14,1,0.0,3.185156e-10,0,1.0
4,4,0,2.308428e-15,2.308431e-15,2.245339e-06,1.866819e-14,0.000000e+00,1.938215e-14,1,0.0,1.383176e-10,0,1.0

In [18]:
final_scores = pd.concat([df, attribute_df], axis=1)

# Reset index after concatenation
final_scores.reset_index(drop=True, inplace=True)

# Display the concatenated DataFrame
final_scores.head

<bound method NDFrame.head of          Unnamed: 0  method_id  refundDecimal        refund  amountDecimal  \
0                 0          0   5.153828e-15  5.153831e-15   8.707997e-07
1                 1          0   1.651061e-13  1.651061e-13   7.272510e-06
2                 2          0   2.229661e-14  2.229661e-14   5.608440e-10
3                 3          0   4.518457e-14  4.518457e-14   5.803177e-07
4                 4          0   2.308428e-15  2.308431e-15   2.245339e-06
...             ...        ...            ...           ...            ...
2655995     2655995         32   5.860874e-10  5.860874e-10   0.000000e+00
2655996     2655996          0   6.576308e-14  6.576308e-14   2.290429e-09
2655997     2655997         28   3.857937e-10  3.857937e-10   2.446795e-07
2655998     2655998          0   7.057750e-14  7.057751e-14   2.277544e-09
2655999     2655999          5   6.791223e-11  6.791223e-11   0.000000e+00

         burnedDecimal  overEstimationBurn   baseFeeBurn  success  \
0         1.909200e-14        1.822014e-15  1.943351e-14        1
1         1.127853e-13        1.984154e-14  1.128663e-13        1
2         1.985343e-14        3.492619e-15  1.986773e-14        1
3         4.086698e-14        7.189436e-15  4.089633e-14        1
4         1.866819e-14        0.000000e+00  1.938215e-14        1
...                ...                 ...           ...      ...
2655995   5.816173e-10        6.773704e-12  6.024161e-10        1
2655996   4.976627e-14        8.283350e-15  4.990264e-14        1
2655997   3.434023e-10        6.013116e-11  3.437089e-10        1
2655998   5.073262e-14        8.444192e-15  5.087163e-14        1
2655999   6.054800e-11        1.037164e-11  6.065125e-11        1

         minerPenalty  ...  exitCode  K Prototypes        date sender_account  \
0                 0.0  ...         0          1.00  2022-01-01      f01203758
1                 0.0  ...         0          1.00  2022-01-01        f033259
2                 0.0  ...         0          1.00  2022-01-01      f01497762
3                 0.0  ...         0          1.00  2022-01-01       f0402394
4                 0.0  ...         0          1.00  2022-01-01       f0215684
...               ...  ...       ...           ...         ...            ...
2655995           0.0  ...         0          0.25  2024-01-28      f01198771
2655996           0.0  ...         0          1.00  2024-01-28      f01049107
2655997           0.0  ...         0          0.25  2024-01-28       f0167207
2655998           0.0  ...         0          1.00  2024-01-28      f01383124
2655999           0.0  ...         0          0.50  2024-01-28       f0883755

                                            sender_address    sender_type  \
0                f1og2qiumoi2ghl6d5iijp5xcfh2q4o7d5xfjjt3y  fil/6/account
1                f1abjxfbp274xpdqcpuaykwkfb43omjotacm2p3za  fil/6/account
2        f3r37kx5m5o5gevr5j57tgh2rskk5gn7gyec7zso2ydran...  fil/6/account
3                f1roupds4r6vqwpp2ytaoj24om2o5qofem4rtcpki  fil/6/account
4                f1yp4jxrdxvm4fopvtqwvr7zgneobyahqoguuh5tq  fil/6/account
...                                                    ...            ...
2655995  f3w5ei3auvnwbdjbs4hq7wqwjzjtop6m4nrbqioylcjxxt...        unknown
2655996          f14lf2lq4nr3g6uojutewr32nlzaii5ypywg5bjuq        unknown
2655997  f3rthxilc5jhxf45ckjltim7ykvopu5lxbqsuyiyjjqf4n...        unknown
2655998          f1zpag6wvamdvpm2w6ws2vhtudp3dfxkpsyi5tzgi        unknown
2655999  f3uf4vwfk7vrnbu23qs3phny2lkdl4wnyli7mx5r2ad62f...        unknown

        receiver_account                           receiver_address  \
0              f01384070  f1dbpj7pfjhy2okcqonqwgjtr42fo3mt7ncd4rdcq
1              f01657723  f1pvehrjw4zjugo4uszgapnpzmslydyld67t2d6ka
2                f084271  f1idgyygmjspqzo2fmuhwkljendzbfnb7jukfxxzi
3              f01614774  f1ajhf7lzj5xhmrmy4t5b3hko4eswtbd7g5hkvgcq
4              f01383260  f1tddhyobxudj3hs7c2ma7cdxmdh427exqykatmoa
...                  ...                                        ...
2655995        f01199028                                  f01199028
2655996        f02883873  f1yiwi5nhwbl7t2n6rmmd6rawf5lmntxqoryndtkq
2655997         f0167254                                   f0167254
2655998        f02883873  f1yiwi5nhwbl7t2n6rmmd6rawf5lmntxqoryndtkq
2655999        f01288529                                  f01288529

         receiver_type method_name
0        fil/6/account    Transfer
1        fil/6/account    Transfer
2        fil/6/account    Transfer
3        fil/6/account    Transfer
4        fil/6/account    Transfer
...                ...         ...
2655995        unknown         NaN
2655996        unknown    Transfer
2655997        unknown         NaN
2655998        unknown    Transfer
2655999        unknown         NaN

[2656000 rows x 21 columns]>

In [19]:
value_counts1 = final_scores['K Prototypes'].value_counts()

print(value_counts1)

K Prototypes
1.00    1377113
0.50     677496
0.25     320324
0.00     197864
0.75      83203
Name: count, dtype: int64

In [20]:
results_data_sender=final_scores[['date','sender_account','K Prototypes']]

grouped_df_sender = results_data_sender.groupby('sender_account').agg({
    'date': 'count', 'K Prototypes':'mean'})

grouped_df_sender = grouped_df_sender.rename(columns={'date': 'count'})
grouped_df_sender.reset_index(inplace=True)

In [21]:
grouped_df_sender = grouped_df_sender.rename(columns={'sender_account': 'account'})
grouped_df_sender.reset_index(inplace=True)

In [22]:
results_data_receiver=final_scores[['date','receiver_account','K Prototypes']]
grouped_df_receiver = results_data_receiver.groupby('receiver_account').agg({
    'date': 'count', 'K Prototypes':'mean'})
grouped_df_receiver= grouped_df_receiver.rename(columns={'date': 'count'})
grouped_df_receiver.reset_index(inplace=True)
grouped_df_receiver = grouped_df_receiver.rename(columns={'receiver_account': 'account'})
grouped_df_receiver.reset_index(inplace=True)

In [23]:
results_final_1=pd.concat([grouped_df_sender,grouped_df_receiver],axis=0)
results_final=results_final_1.groupby('account').agg({
    'count': 'sum', 'K Prototypes':'mean'})
results_final.reset_index(inplace=True)

In [24]:
results_final.head(50)

      account  count  K Prototypes
0         f00    302      0.250000
1         f01    301      0.250000
2        f010    191      0.219895
3    f0100008      1      1.000000
4    f0100016      1      1.000000
5    f0100021      2      1.000000
6    f0100023      6      1.000000
7    f0100027    151      0.777027
8    f0100033    169      0.380178
9    f0100034     38      0.500000
10   f0100056    223      1.000000
11   f0100057    214      0.730769
12   f0100059     38      0.500000
13   f0100061     26      0.682692
14   f0100066    219      0.450913
15   f0100081     14      0.482143
16   f0100082    335      0.388060
17   f0100085      1      1.000000
18   f0100086     43      1.000000
19   f0100090     41      0.493902
20   f0100096      1      1.000000
21    f010010    111      0.470721
22   f0100104      1      1.000000
23   f0100113      8      1.000000
24   f0100115      2      0.625000
25   f0100116     41      0.493902
26   f0100126   3543      1.000000
27   f0100132     12      1.000000
28   f0100147      3      1.000000
29  f01001492      1      1.000000
30   f0100158      2      1.000000
31   f0100172      1      1.000000
32   f0100174    129      0.484496
33   f0100180      3      1.000000
34  f01001842      4      1.000000
35   f0100185      2      1.000000
36  f01001869      2      1.000000
37  f01001888     15      1.000000
38  f01001909     19      1.000000
39  f01001920      4      0.812500
40  f01001930      2      1.000000
41  f01001931      1      1.000000
42  f01001935      1      1.000000
43   f0100195      2      1.000000
44  f01001957      1      1.000000
45  f01001960      2      1.000000
46   f0100197      1      1.000000
47  f01001971     13      1.000000
48  f01001974      6      1.000000
49  f01001975      5      1.000000

In [25]:
# Assuming 'df' is your DataFrame
rows_f681832= results_final[results_final['account'] == 'f090896']
rows_f01628199= results_final[results_final['account'] == 'f01628199']
rows_f01438385= results_final[results_final['account'] == 'f01438385']
rows_f0480190= results_final[results_final['account'] == 'f0480190']
# Display or use the extracted rows
print(rows_f681832)
print(rows_f01628199)
print(rows_f01438385)
print(rows_f0480190)

        account  count  K Prototypes
464527  f090896     27      0.509259
          account  count  K Prototypes
105690  f01628199    143      0.475524
         account  count  K Prototypes
63031  f01438385    170      0.498529
         account  count  K Prototypes
438031  f0480190     45          0.45

In [78]:
rows_f01956427= results_final[results_final['account'] == 'f01956427']
rows_f01928087= results_final[results_final['account'] == 'f01928087']

rows_f0100174= results_final[results_final['account'] == 'f0100174']
rows_f0100126= results_final[results_final['account'] == 'f0100126']

print(rows_f01956427)
print(rows_f01928087)
print(rows_f0100174)
print(rows_f0100126)

          account  count  K Prototypes
229021  f01956427    153           1.0
          account  count  K Prototypes
216039  f01928087     25           1.0
     account  count  K Prototypes
32  f0100174    129      0.484496
     account  count  K Prototypes
26  f0100126   3543           1.0

In [79]:
users=['f0101498','f0101498','f01015802','f01012','f010088','f681832', 'f01628199', 'f01438385', 'f0480190', 'f01956427', 'f01928087', 'f0100174', 'f0100126','f01015701','f0100963']
for user in users: 
    row=results_final[results_final['account'] == user]
    print(row)

      account  count  K Prototypes
261  f0101498     57           1.0
      account  count  K Prototypes
261  f0101498     57           1.0
       account  count  K Prototypes
319  f01015802     54           1.0
    account  count  K Prototypes
213  f01012    336      0.429315
     account  count  K Prototypes
162  f010088    520      0.435577
Empty DataFrame
Columns: [account, count, K Prototypes]
Index: []
          account  count  K Prototypes
105690  f01628199    143      0.475524
         account  count  K Prototypes
63031  f01438385    170      0.498529
         account  count  K Prototypes
438031  f0480190     45          0.45
          account  count  K Prototypes
229021  f01956427    153           1.0
          account  count  K Prototypes
216039  f01928087     25           1.0
     account  count  K Prototypes
32  f0100174    129      0.484496
     account  count  K Prototypes
26  f0100126   3543           1.0
       account  count  K Prototypes
303  f01015701    100         0.435
      account  count  K Prototypes
173  f0100963    118           1.0